# --- Decoupling from systemd-resolved  ---

# Listen only on the local loopback interface and the node's static IP
listen-address=127.0.0.1,10.10.10.30

# We strictly bind sockets only to the specified addresses (we do not bind to 0.0.0.0)
bind-interfaces

# --- Upstream and loop protection ---

# Ignore /etc/resolv.conf to avoid a loop with systemd-resolved
no-resolv

# Specify upstream DNS - the libvirt network gateway (it knows the way to the internet) 
server=10.10.10.1

# --- Zone settings and network hygiene ---

# Names from this zone are served only locally and are never forwarded upstream
local=/lab.internal/

# Default domain suffix
domain=lab.internal

# Do not send short, incomplete names externally
domain-needed

# Do not send reverse PTR queries for private address ranges to the outside
bogus-priv

# DNS Response Cache Size
cache-size=1000

# --- Static DNS Records (A Record + Automatic PTR) ---

host-record=web.lab.internal,10.10.10.10
host-record=app.lab.internal,10.10.10.20
host-record=mgmt.lab.internal,10.10.10.30
